version: '2'
services:
  node:
    image: "node:10"
    user: "node"
    working_dir: /usr/src/graphal-server-example
    environment:
      - NODE_ENV=development
    command: npm run start
    volumes:
      - .:/usr/src/graphal-server-example
    ports:
      - "4000:4000"